export enum MapArea {
	Unknown = 0,
	Top = 1 << 0,
	Middle = 1 << 1,
	Bottom = 1 << 2,
	River = 1 << 3,
	RadiantBase = 1 << 4,
	DireBase = 1 << 5,
	RoshanPit = 1 << 6,
	DireBottomJungle = 1 << 7,
	DireTopJungle = 1 << 8,
	RadiantBottomJungle = 1 << 9,
	RadiantTopJungle = 1 << 10,
	Jungle = DireBottomJungle | DireTopJungle | RadiantBottomJungle | RadiantTopJungle,
}
