export enum DOTAHullSize {
	DOTA_HULL_SIZE_SMALL = 8,
	DOTA_HULL_SIZE_REGULAR = 16,
	DOTA_HULL_SIZE_SIEGE = 16,
	DOTA_HULL_SIZE_HERO = 24,
	DOTA_HULL_SIZE_HUGE = 80,
	DOTA_HULL_SIZE_BUILDING = 81,
	DOTA_HULL_SIZE_FILLER = 96,
	DOTA_HULL_SIZE_BARRACKS = 144,
	DOTA_HULL_SIZE_TOWER = 144,
}