export const enum DAMAGE_AMPLIFY {
	DAMAGE_AMPLIFY_NONE = -1,
	DAMAGE_AMPLIFY_INCOMING = 1 << 0,
	DAMAGE_AMPLIFY_OUTGOING = 1 << 1,
	DAMAGE_AMPLIFY_ALL = DAMAGE_AMPLIFY_INCOMING | DAMAGE_AMPLIFY_OUTGOING
}
