export enum DOTAHullSize {
	DOTA_HULL_SIZE_NONE,
	DOTA_HULL_SIZE_SMALLEST,
	DOTA_HULL_SIZE_SMALL,
	DOTA_HULL_SIZE_REGULAR,
	DOTA_HULL_SIZE_HERO,
	DOTA_HULL_SIZE_BIG_HERO,
	DOTA_HULL_SIZE_SIEGE,
	DOTA_HULL_SIZE_TOWER,
	DOTA_HULL_SIZE_LARGE,
	DOTA_HULL_SIZE_HUGE,
	DOTA_HULL_SIZE_BUILDING,
	DOTA_HULL_SIZE_BARRACKS,
	DOTA_HULL_SIZE_FILLER
}
