/* eslint-disable @typescript-eslint/naming-convention */
export const DOTA_UNIT_TARGET_FLAGS = {
	DOTA_UNIT_TARGET_FLAG_NONE: 0n,
	DOTA_UNIT_TARGET_FLAG_RANGED_ONLY: 2n,
	DOTA_UNIT_TARGET_FLAG_MELEE_ONLY: 4n,
	DOTA_UNIT_TARGET_FLAG_DEAD: 8n,
	DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES: 16n,
	DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES: 32n,
	DOTA_UNIT_TARGET_FLAG_INVULNERABLE: 64n,
	DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE: 128n,
	DOTA_UNIT_TARGET_FLAG_NO_INVIS: 256n,
	DOTA_UNIT_TARGET_FLAG_CAN_BE_SEEN: 384n,
	DOTA_UNIT_TARGET_FLAG_NOT_ANCIENTS: 512n,
	DOTA_UNIT_TARGET_FLAG_PLAYER_CONTROLLED: 1024n,
	DOTA_UNIT_TARGET_FLAG_NOT_DOMINATED: 2048n,
	DOTA_UNIT_TARGET_FLAG_NOT_SUMMONED: 4096n,
	DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS: 8192n,
	DOTA_UNIT_TARGET_FLAG_NOT_ATTACK_IMMUNE: 16384n,
	DOTA_UNIT_TARGET_FLAG_MANA_ONLY: 32768n,
	DOTA_UNIT_TARGET_FLAG_CHECK_DISABLE_HELP: 65536n,
	DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO: 131072n,
	DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD: 262144n,
	DOTA_UNIT_TARGET_FLAG_NOT_NIGHTMARED: 524288n,
	DOTA_UNIT_TARGET_FLAG_PREFER_ENEMIES: 1048576n,
	DOTA_UNIT_TARGET_FLAG_RESPECT_OBSTRUCTIONS: 2097152n
}
export type DOTA_UNIT_TARGET_FLAGS = bigint
