/* eslint-disable @typescript-eslint/naming-convention */
export const DOTA_UNIT_TARGET_TEAM = {
	DOTA_UNIT_TARGET_TEAM_NONE: 0n,
	DOTA_UNIT_TARGET_TEAM_FRIENDLY: 1n,
	DOTA_UNIT_TARGET_TEAM_ENEMY: 2n,
	DOTA_UNIT_TARGET_TEAM_BOTH: 3n,
	DOTA_UNIT_TARGET_TEAM_CUSTOM: 4n
}
export type DOTA_UNIT_TARGET_TEAM = bigint
