/* eslint-disable @typescript-eslint/naming-convention */
export const DOTA_UNIT_TARGET_TYPE = {
	DOTA_UNIT_TARGET_NONE: 0n,
	DOTA_UNIT_TARGET_HERO: 1n,
	DOTA_UNIT_TARGET_CREEP: 2n,
	DOTA_UNIT_TARGET_BUILDING: 4n,
	DOTA_UNIT_TARGET_COURIER: 16n,
	DOTA_UNIT_TARGET_HEROES_AND_CREEPS: 19n,
	DOTA_UNIT_TARGET_OTHER: 32n,
	DOTA_UNIT_TARGET_ALL: 55n,
	DOTA_UNIT_TARGET_TREE: 64n,
	DOTA_UNIT_TARGET_CUSTOM: 128n,
	DOTA_UNIT_TARGET_SELF: 256n,
	DOTA_UNIT_TARGET_BASIC: 18n
}
export type DOTA_UNIT_TARGET_TYPE = bigint
