export enum SPELL_IMMUNITY_TYPES {
	SPELL_IMMUNITY_NONE = 0,
	SPELL_IMMUNITY_ALLIES_YES = 1,
	SPELL_IMMUNITY_ALLIES_NO = 2,
	SPELL_IMMUNITY_ENEMIES_YES = 3,
	SPELL_IMMUNITY_ENEMIES_NO = 4,
	SPELL_IMMUNITY_ALLIES_YES_ENEMIES_NO = 5
}
